%*************************************************************************
% FUNCTION FOR PROPAGATING EQUATIONS OF MOTION USING VELOCITY VERLET ALGORITHM
function [RX,RY,RZ,VX,VY,VZ,FX,FY,FZ,EKIN,EPOT,ETOT,PRESS] = vverlet(RX,RY,RZ,VX,VY,VZ,FX,FY,FZ,NATOM,DENS,kT,SIGMA,EPSILON,MASS,LJCUT,DT,RESCALE)
%*************************************************************************

% CALCULATE SIMULATION BOX LENGTH AND SQUARE OF LJCUT
LSIMBOX = (NATOM/DENS)^(1.0/3.0);

% CALCULATE HALF TIMESTEP
DT2 = DT/2.0;

% ADVANCE POSITIONS FROM T TO T+DT AND VELOCITIES FROM T TO T+DT/2 
% ACCORDING TO THE VELOCITY VERLET INTEGRATOR:
%  V(T+DT/2) = V(T) + 1/2*DT*A(T)
%  R(T+DT)   = R(T) + DT*V(T) + 1/2*(DT**2)*A(T)
%  V(T+DT)   = V(T+DT/2) + 1/2*DT*A(T+DT)

%	ADVANCE POSITIONS BY DT AND VELOCITIES BY DT/2
for I = 1:NATOM
	VX(I) = VX(I) + DT2*FX(I)/MASS;
	VY(I) = VY(I) + DT2*FY(I)/MASS;
	VZ(I) = VZ(I) + DT2*FZ(I)/MASS;
    
	RX(I) = RX(I) + DT*VX(I);
	RY(I) = RY(I) + DT*VY(I);
	RZ(I) = RZ(I) + DT*VZ(I);
end

% CALCULATE FORCES
[FX,FY,FZ,EPOT,PRESS] = forces(RX,RY,RZ,NATOM,DENS,SIGMA,EPSILON,LJCUT);

% ADVANCE VELOCITIES BY THE REMAINING DT/2, WITH NEW FORCES
for I = 1:NATOM
	VX(I) = VX(I) + DT2*FX(I)/MASS;
	VY(I) = VY(I) + DT2*FY(I)/MASS;
	VZ(I) = VZ(I) + DT2*FZ(I)/MASS;
end
	
% APPLY PERIODIC BOUNDARY CONDITIONS                 
for I = 1:NATOM
	RX(I) = RX(I) - LSIMBOX*round(RX(I)/LSIMBOX);
	RY(I) = RY(I) - LSIMBOX*round(RY(I)/LSIMBOX);
	RZ(I) = RZ(I) - LSIMBOX*round(RZ(I)/LSIMBOX);
end

% RESCALE THE VELOCITIES TO THE OBTAIN THE SETPOINT TEMPERATURE. DO 
% THIS ONLY DURING THE EQUILIBRATION
if (RESCALE) 
	VELSQ = 0.0;
	for I = 1:NATOM
        VELSQ = VELSQ + MASS*(VX(I)^2 + VY(I)^2 + VZ(I)^2);
	end
	FACTOR = sqrt(3.0*NATOM*kT/VELSQ);
	for I = 1:NATOM
        VX(I) = VX(I)*FACTOR;
        VY(I) = VY(I)*FACTOR;
        VZ(I) = VZ(I)*FACTOR;
    end
end

% CALCULATE CURRENT KINETIC ENERGY
EKIN = 0.0;
for I = 1:NATOM
	EKIN = EKIN + VX(I)^2 + VY(I)^2 + VZ(I)^2;
end
EKIN = EKIN*MASS/2;

% CALCULATE TOTAL ENERGY AS KINETIC ENERGY + POTENTIAL ENERGY
ETOT = EKIN + EPOT;
	
% ADD CURRENT KINETIC (IDEAL GAS) CONTRIBUTION TO CURRENT PRESSURE
PRESS = PRESS + 2.0*EKIN*DENS/3.0/NATOM;


      

